{
 "title": "IRIS Bench",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Carbon Forecast gCO2/kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "carbon_forecast{region=\"South_England\"}",
     "legendFormat": "South_England"
    }
   ]
  },
  {
   "title": "Mantid Imaging - Reconstruct 4 GB Benchmark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "power_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "power_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "power_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "power_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "power_gpu1{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU1"
    },
    {
     "expr": "power_gpu0{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "util_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "util_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "util_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "util_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "util_gpu0{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    },
    {
     "expr": "util_gpu1{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "mem_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_gpu0{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    },
    {
     "expr": "mem_gpu1{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "temp_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "temp_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "temp_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "temp_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "temp_gpu0{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    },
    {
     "expr": "temp_gpu1{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU1"
    }
   ]
  },
  {
   "title": "GPU Memory Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "mem_clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    },
    {
     "expr": "mem_clk_speed_gpu1{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU1"
    },
    {
     "expr": "mem_clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "mem_clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  },
  {
   "title": "GPU Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU0"
    },
    {
     "expr": "clk_speed_gpu1{benchmark=\"mantid_run_4\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}} GPU1"
    },
    {
     "expr": "clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "clk_speed_gpu0{benchmark=\"mantid_run_4\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  },
  {
   "title": "Benchmark Results",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "mantid_run_4_time unless (mantid_run_4_time == (mantid_run_4_time offset $__interval))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sciml Bench - Stemdl Classification Benchmark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "power_gpu0{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "power_gpu1{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "power_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "util_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "util_gpu1{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "util_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "temp_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "temp_gpu1{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "temp_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "mem_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "mem_gpu1{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "mem_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "GPU Clock Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "clk_speed_gpu1{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "GPU Clock Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "clk_speed_gpu1{benchmark=\"stemdl_classification\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=\"stemdl_classification\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Benchmark Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "stemdl_classification_time unless (stemdl_classification_time == (stemdl_classification_time offset $__interval))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sciml Bench - Synthetic Regression Benchmark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "power_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "util_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "temp_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "mem_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "mem_clk_speed_gpu1{benchmark=\"synthetic_regression\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "mem_clk_speed_gpu1{benchmark=\"synthetic_regression\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=\"synthetic_regression\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Benchmark Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "synthetic_regression_time unless (synthetic_regression_time == (synthetic_regression_time offset $__interval))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Mantid Imaging - Reconstruct 1GB Benchmark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "power_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "power_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "util_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "util_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "mem_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "temp_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "temp_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "mem_clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "mem_clk_speed_gpu1{benchmark=~\"mantid_run_1|run_1\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "mem_clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "GPU Clock Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_RTX_A4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU0"
      },
      {
       "expr": "clk_speed_gpu1{benchmark=~\"mantid_run_1|run_1\",device_count=\"2\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}} GPU1"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Quadro_RTX_4000\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"NVIDIA_A100_80GB_PCIe\"}",
       "legendFormat": "{{gpu_name}}"
      },
      {
       "expr": "clk_speed_gpu0{benchmark=~\"mantid_run_1|run_1\",device_count=\"1\",gpu_name=\"Tesla_V100-PCIE-32GB\"}",
       "legendFormat": "{{gpu_name}}"
      }
     ]
    },
    {
     "title": "Benchmark Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "(mantid_run_1_time or run_1_time) unless (mantid_run_1_time or run_1_time == (mantid_run_1_time or run_1_time offset $__interval))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}