# Use an ARG to specify the base image, with a default value
ARG BASE_IMAGE=harbor.stfc.ac.uk/stfc-cloud-staging/iris-bench/sciml_base:latest

# Use the specified base image
FROM ${BASE_IMAGE}

# Set the working directory
WORKDIR /root

# Install the benchmark
RUN /bin/bash -c "source /root/anaconda3/bin/activate bench && \
    sciml-bench install stemdl_classification && \
    sciml-bench download stemdl_ds1"

# Set the entrypoint to run the benchmark
ENTRYPOINT ["/bin/bash", "-c", "source /root/anaconda3/bin/activate bench && sciml-bench run stemdl_classification --output_dir=/root/results/ -b epochs 10 -b gpus -1"]