# Use the official Ubuntu base image
FROM ghcr.io/bryceshirley/mantid_base:latest

# Set the working directory
WORKDIR /root

# Set the entrypoint to run the benchmark
CMD ["/bin/bash", "-c", "cd /root/mantid_imaging_cloud_bench && ./run_1.sh"]