# Use the harbor image by default, but allow override to use a local image
ARG BASE_IMAGE=harbor.stfc.ac.uk/stfc-cloud-staging/iris-bench/sciml_base:latest
FROM ${BASE_IMAGE}

# Set the working directory
WORKDIR /root

# Install the benchmark
RUN /bin/bash -c "source /root/anaconda3/bin/activate bench && \
    sciml-bench install stemdl_classification && \
    sciml-bench download stemdl_ds1"

# Set the entrypoint to run the benchmark
ENTRYPOINT ["/bin/bash", "-c", "source /root/anaconda3/bin/activate bench && sciml_bench --output_dir=/root/results/ -b epochs 1 -gpus 2 stemdl_classification"]