# Use the official Ubuntu base image
FROM harbor.stfc.ac.uk/stfc-cloud-staging/iris-bench/mantid_base:latest

# Set the working directory
WORKDIR /root

# Set the entrypoint to run the benchmark
CMD ["/bin/bash", "-c", "cd /root/mantid_imaging_cloud_bench && ./run_8.sh"]