# Use the official Ubuntu base image
FROM ubuntu:20.04

# Set the working directory
WORKDIR /root

# Set the entrypoint to run the benchmark
ENTRYPOINT ["/bin/bash", "-c", "echo 'Starting sleep period: 5 mins...' && sleep 300 && echo 'Complete.'"]